// thanks for: https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-api/src/trace/span_context.ts

export interface TraceContext {
	/**
	 * The ID of the trace that this span belongs to. It is worldwide unique
	 * with practically sufficient probability by being made as 16 randomly
	 * generated bytes, encoded as a 32 lowercase hex characters corresponding to
	 * 128 bits.
	 */
	traceId: string;
	/**
	 * The ID of the Span. It is globally unique with practically sufficient
	 * probability by being made as 8 randomly generated bytes, encoded as a 16
	 * lowercase hex characters corresponding to 64 bits.
	 */
	spanId: string;
	/**
	 * Only true if the SpanContext was propagated from a remote parent.
	 */
	isRemote?: boolean;
}
