export interface TraceContext {
	/**
	 * The ID of the trace that this span belongs to. It is worldwide unique
	 * with practically sufficient probability by being made as 16 randomly
	 * generated bytes, encoded as a 32 lowercase hex characters corresponding to
	 * 128 bits.
	 */
	traceId: string;
	/**
	 * The ID of the Span. It is globally unique with practically sufficient
	 * probability by being made as 8 randomly generated bytes, encoded as a 16
	 * lowercase hex characters corresponding to 64 bits.
	 */
	spanId: string;
}
